import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
import GetIn from "@/components/GetIn";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const miracle = localFont({
  src: "./../fonts/Miracle.woff2",
  display: "swap",
  variable: "--font-miracle",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${miracle.variable} ${inter.variable}`}>
        <Header />
        {children}
        <GetIn />
        <Footer />
      </body>
    </html>
  );
}
